# Generated by Django 2.0.4 on 2018-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcrequest',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gcrequest',
            name='longitde',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
