# Generated by Django 2.0.4 on 2018-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_auto_20180412_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcrequest',
            name='image',
            field=models.ImageField(default='images/img.png', upload_to='images/%Y/%m/'),
        ),
    ]
