# Generated by Django 2.0.4 on 2018-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_gcrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcrequest',
            name='status',
            field=models.CharField(choices=[('Not responded yet', 'Not responded yet'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Not responded yet', max_length=1),
        ),
    ]
