# Generated by Django 2.0.4 on 2018-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_auto_20180413_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcrequest',
            options={'verbose_name': 'Garbage Collection Request', 'verbose_name_plural': 'Garbage Collection Requests'},
        ),
        migrations.AlterField(
            model_name='gcrequest',
            name='image',
            field=models.ImageField(default='images/img.png', upload_to='request_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='gcrequest',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='gcrequest',
            name='longitde',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
    ]
