# Generated by Django 2.0.4 on 2018-04-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_auto_20180415_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcrequest',
            old_name='req_date',
            new_name='requested_on',
        ),
    ]
