# Generated by Django 2.0.4 on 2018-04-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_auto_20180415_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcrequest',
            options={'verbose_name': 'Garbage Collection Request'},
        ),
    ]
